name: Python Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'

    - name: Install system dependencies (Google Chrome and ChromeDriver)
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable chromium-chromedriver

    - name: Check Google Chrome path
      run: which google-chrome

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests with pytest and generate Allure report
      run: |
        # Set the Chrome binary location and ensure Google Chrome is found
        export CHROME_BIN=$(which google-chrome)
        echo "Using Chrome binary: $CHROME_BIN"
        pytest tests_ui_layout/ --alluredir=allure-results

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-results/
