name: Python Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest  # Switch to Windows runner

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1' 

    - name: Install system dependencies (Google Chrome and ChromeDriver)
      run: |
        # Install Google Chrome
        choco install googlechrome
        
        # Install ChromeDriver
        choco install chromedriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests with pytest and generate Allure report
      run: |
        pytest -s tests_ui_layout/ --alluredir=allure-results

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-results/
