name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

            # Install Google Chrome
      - name: Install Google Chrome
        run: |
          # Install ChromeDriver matching the installed Google Chrome version
          VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //')
          wget https://chromedriver.storage.googleapis.com/$(echo $VERSION | cut -d '.' -f1)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y chromium-chromedriver

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
