name: Python Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: windows-latest  

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1' 

    - name: Install system dependencies (Google Chrome and ChromeDriver)
      run: |
        # Install Google Chrome
        choco install googlechrome
        
        # Install ChromeDriver
        choco install chromedriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests with pytest and generate Allure report
      run: |
        pytest -s tests_ui_layout/ --alluredir=allure-results

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-results/

    - name: Load Allure report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: allure-history

    - name: Build Allure report
      uses: simple-elf/allure-report-action@v1.11
      if: always()
      with:
          gh_pages: allure-history
          allure_results: promptSecurity-automation/allure-results
          allure_report: allure-report
          allure_history: allure-history
          report_url: ${{ env.report_url }}

    - name: Publish UI Allure report
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          enable_jekyll: false
