name: Python Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1' 

    - name: Install system dependencies (Chrome and ChromeDriver)
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests with pytest and generate Allure report
      run: |
        pytest tests_ui_layout/ --alluredir=allure-results

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-results/
